### ISSUE TITLE
redis broker?

### ISSUE THREAD

**Issue by foobargeez** [gofort/dispatcher#1]
Hi,
Do you have any plans to support redis as broker (for job queues and results)?

Thanks!

**Comment by gofort** [comment]
Hello @foobargeez! No i don't have such plans. You can use https://github.com/RichardKnop/machinery which already has it.

**Comment by foobargeez** [comment]
Thanks!  I use machinery currently (and it works well) but the [lack](https://github.com/RichardKnop/machinery/issues/121) of `Graceful quit (stop all workers, wait until all tasks will be finished, close connection)` or `warm shutdown` is what made me to look at alternatives and I came across dispatcher.
