### ISSUE TITLE
Worker not closed when queue was manually deleted

### ISSUE THREAD

**Issue by rimantoro** [gofort/dispatcher#2]
Hi,

I'm trying to implement this worker codes.

https://github.com/gofort/dispatcher/blob/7c1dd4ae7c2a3e8a24ab477dd7416e5fdf4c3c86/examples/worker/worker.go

And found a bugs or maybe I'm missing something. The worker is not closed when the queue already deleted in RabbitMQ.

Step to reproduce

1. Start worker
2. Delete related queue in RabbitMQ admin
3. Back to worker and press ctrl+C, its will start closing process but it never finished

```Bash
^CDEBU[0090] [Starting AMQP connection closing]            source=dispatcher
DEBU[0090] [Starting global shutoff: close publisher, stop workers consuming, wait for all tasks to be finished]  source=dispatcher
DEBU[0090] [Deactivating publisher]                      source=dispatcher
DEBU[0090] [Stopping automatic AMQP reconnection]        source=dispatcher
DEBU[0090] [Publisher is deactivated]                    source=dispatcher
INFO[0090] [Waiting for all workers to be done]          source=dispatcher
DEBU[0090] Worker [disb_1] closing started               source=dispatcher
```

Is it supposed to be like that, or those codes its not implementing auto restart when have deleted queue signals ?

**Comment by gofort** [comment]
Hi! It is rather hard for me to answer your question because I don't use and support this project now ;( You can always fork and fix any issue which you see. Thanks!
